schema = 3

[mod]
  [mod."github.com/Songmu/gitconfig"]
    version = "v0.2.0"
    hash = "sha256-iL0Eeiic/bxc8Gs2vrPINuZsVfFZz4F68Ax3fR2TyNw="
  [mod."github.com/cli/go-gh"]
    version = "v1.2.1"
    hash = "sha256-J3GR5lorBg3fjTXJT8214TUZclPKlRndnhTm3OhZJRc="
  [mod."github.com/cli/safeexec"]
    version = "v1.0.1"
    hash = "sha256-74r/MHyMIxDSGA2D862d/OQ3lYLozxoUIRMyL0n03m8="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.6"
    hash = "sha256-wJnHgp+NPchXkR71ARLMjo4VryzgGkz2tYWPsC+3eFo="
  [mod."github.com/daviddengcn/go-colortext"]
    version = "v1.0.0"
    hash = "sha256-iOjKdkfIqKA61uq4Mw+6RHaVMnz0xWjtaMgcNR5vtEg="
  [mod."github.com/goccy/go-yaml"]
    version = "v1.16.0"
    hash = "sha256-RpDZTl7Rh6R2FDG7UChmtcHPUVb1J6lpbfUd7UD2uSM="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/motemen/go-colorine"]
    version = "v0.0.0-20180816141035-45d19169413a"
    hash = "sha256-KIQD4J9SVS3oYPHoKO+sWmNRN/3UHgFkdkEbkQA2vtU="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/saracen/walker"]
    version = "v0.1.4"
    hash = "sha256-7xzq7TmN/ykhf/UiiZFy+HJUxryllKue4++Dy1b+Ip4="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.27.6"
    hash = "sha256-u4yUgMwphs/7iwkhWrLgsHZru1InycgvY2ZmuxHQeLI="
  [mod."github.com/xrash/smetrics"]
    version = "v0.0.0-20240521201337-686a1a2994c1"
    hash = "sha256-CsyN59w6sKERDI5kkdpq0YKmqdixyCHuN4FYE/56/BQ="
  [mod."golang.org/x/net"]
    version = "v0.38.0"
    hash = "sha256-iHmyxkZQLw1PsUZaXHMt84GrjbXPvkEc92sLoK3W++c="
  [mod."golang.org/x/sync"]
    version = "v0.12.0"
    hash = "sha256-lPIbI6aXx+iKtFjPaXKNLEnuNfhHCVl7EQiE7alUvlM="
  [mod."golang.org/x/sys"]
    version = "v0.31.0"
    hash = "sha256-aulv5obCrhheMlSq7seUgP3C29nfZABwiQ4IBNisgME="
  [mod."golang.org/x/text"]
    version = "v0.23.0"
    hash = "sha256-TiYX1K4DYpP1dEV06whOm43xyOntjrPFi+VAdncoeCY="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
